---
- hosts: web_servers
  become: true
  tasks:
    - name: Update repo and Install nginx
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Create folder for website
      file:
        path: /var/www/{{ website_name }}
        state: directory

    - name: Delete sites-enable and sites-available files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default
      notify:
        - Restart nginx

    - name: Add webpage to web_servers
      template:
        src: index.html.j2
        dest: /var/www/{{ website_name }}/index.html
      notify:
        - Restart nginx

    - name: Configure nginx with new config file
      template:
        src: default.j2
        dest: /etc/nginx/sites-available/{{ website_name }}
      notify:
        - Restart nginx

    - name: Create symlink for config files
      file:
        src: /etc/nginx/sites-available/{{ website_name }}
        dest: /etc/nginx/sites-enabled/{{ website_name }}
        state: link
      notify:
        - Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
